from env import TREE_OPENAI_API_KEY, TREE_TREE_PATH, TREE_LOGS_DIR, TREE_ARCHIVE_DIR

print("🔑 OPENAI_API_KEY:", TREE_OPENAI_API_KEY)
print("📄 TREE_PATH:", TREE_TREE_PATH)
print("📂 LOGS_DIR:", TREE_LOGS_DIR)
print("📂 ARCHIVE_DIR:", TREE_ARCHIVE_DIR)
